heat_template_version: 2018-03-02

description: Minecraft

parameters:
  net:
    description: name of network used to launch instance.
    type: string
    default: default

resources:
  minecraft:
    type: OS::Nova::Server
    properties:
      image: fedora-coreos-36.20220806.3.0-openstack.x86_64
      # key_name: laptop
      flavor: g3.medium.auto-destruct
      networks:
        - network: { get_param: net }
        - port: { get_resource: mc_port }
      user_data:
        get_file: https://raw.githubusercontent.com/Arunscape/devops/main/minecraft.bu


  mc_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net }
      security_groups: [{ get_resource: security_group }]

  association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: c312d85c-891b-4cff-ab94-0a5e57c09247
      port_id: { get_attr: [minecraft, addresses, { get_param: net }, 0, port] }

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: minecraft }
      volume_id: 29f30b4b-2399-4759-950f-d3dea67df415
      # /dev/disk/by-id/virtio-29f30b4b-2399-4759-950f-d3dea67df415

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: mc_securitygroup
      description: allow SSH and 25565 and icmp
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 25565
          port_range_max: 25565
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp