#cloud-config
users:
  - name: rocky
    groups: wheel
    lock_passwd: false
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHVMzs2dfpHbo76Yuu4tylF4CdRLmwDi1Ni1SwN2FB/8 arunscape@pop-os