---
- name: Update Package Cache
  apt:
    name:
    update_cache: yes
    upgrade: yes

- name: Install packages
  apt:
    name:
    - neovim
    - python-is-python3
    - python3-pip
    - podman
    - podman-docker
    - podman-compose
    - ansible
    state: latest

# - name: Install podman-compose  
#   shell: |
#     mkdir -p ~/.local/bin
#     curl -o ~/.local/bin/podman-compose https://raw.githubusercontent.com/containers/podman-compose/devel/podman_compose.py
#     chmod +x ~/.local/bin/podman-compose

- name: Enable podman.service
  systemd:
    name: podman.service
    enabled: yes
    state: started

- name: Add subuid and subgid for podman
  shell: |
    sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 {{ ansible_env.USER }}
  become: yes

# - name: Podman unshare
#   shell: |
#       podman unshare chown  